// Generated by https://quicktype.io

export interface BerriesListResponse {
    count:    number;
    next:     string;
    previous: null;
    results:  Berries[];
}

export interface Berries {
    name: string;
    url:  string;
}
